% designEqFilt_test
clear; clc; close all;

% energyfl permet d'obtenir une réponse plate à O dB, c'est pratique pour
% égaliser un signal (i.e. appliquer des gains dans chaque bande)

filtParam = struct(...
    'type',1,...
    'rp',1,...
    'rs',60,...
    'fs',48e3,...
    'fmin',60.,...
    'fmax',8000.,...
    'noct',1,...
    'order',12,...
    'lateralBands',1,...
    'energyfl',1,...
    'plotfl',1);

filterBank = designEqFilt(filtParam);

filtParam = struct(...
    'type',2,...
    'rp',0.5,...
    'rs',60,...
    'fs',48e3,...
    'fmin',60.,...
    'fmax',8000.,...
    'noct',1,...
    'order',12,...
    'energyfl',1,...
    'plotfl',1);

filterBank = designEqFilt(filtParam);

filtParam = struct(...
    'type',3,...
    'rp',0.5,...
    'rs',60,...
    'fs',48e3,...
    'fmin',60.,...
    'fmax',8000.,...
    'noct',1,...
    'order',12,...
    'energyfl',1,...
    'plotfl',1);

filterBank = designEqFilt(filtParam);

% Cheby II à la rue !



% TODO : errors with energyfl = 1 (see what is going on)
% TODO : add filtParam.filtertype to choose between different types of
% filters (not only Butterworth)