% designEqFilt_test
clear; clc; close all;

filtParam = struct(...
    'fs',48e3,...
    'fmin',60.,...
    'fmax',8000.,...
    'noct',1,...
    'order',12,...
    'energyfl',0,...
    'plotfl',1);

filterBank = designEqFilt(filtParam);

% TODO : errors with energyfl = 1 (see what is going on
% TODO : add filtParam.filtertype to choose between different types of
% filters (not only Butterworth)